/*
 * Copyright (C) 2019-2026, Advanced Micro Devices. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

/*
 * C implementation of exp double precision 128-bit vector version (v2d)
 *
 * Signature:
 *   v_f64x2_t vrd2_exp(v_f64x2_t x)
 *
 * Algorithm: Table-based range reduction with 64-entry table + degree-5 polynomial
 *
 *   Range reduction and reconstruction follow the scalar exp() fast path
 *   (src/optimized/exp.c), with Sollya-minimax coefficients tuned for vrd2_exp.
 *
 * Implementation Notes
 * ----------------------
 *
 * 1. Argument Reduction:
 *      e^x = 2^(x/ln2) = 2^(x*(64/ln(2))/64)           --- (1)
 *
 *      Choose 'n' and 'f', such that
 *      x * 64/ln2 = n + f                                --- (2)
 *                                     where n is integer, |f| <= 0.5
 *
 *      Choose 'm' and 'j' such that,
 *      n = (64 * m) + j                                  --- (3)
 *                                     where 0 <= j < 64
 *
 *      From (1), (2) and (3),
 *      e^x = 2^((64*m + j + f)/64)
 *          = (2^m) * (2^(j/64)) * 2^(f/64)
 *          = (2^m) * (2^(j/64)) * e^(f*(ln(2)/64))
 *
 * 2. Table Lookup:
 *      Values of (2^(j/64)) are precomputed for j = 0, 1, 2 ... 63,
 *      stored as {head, tail} double-double pairs (~106-bit precision):
 *        head = double(2^(j/64))         — best 53-bit approximation
 *        tail = double(2^(j/64) - head)  — error term (bits 54-106)
 *      Table data: src/optimized/data/_exp_tbl_64_2field.data
 *      Generated by: tools/sollya/gen_exp_tbl_2field.sollya
 *
 * 3. Polynomial Evaluation:
 *      From (2),
 *        f = x*(64/ln(2)) - n
 *      Let,
 *        r = f*(ln(2)/64) = x - n*(ln(2)/64)
 *
 *      Since |f| <= 0.5, we have |r| <= ln(2)/128 ≈ 0.0054.
 *      This narrow range allows a degree-5 Sollya minimax polynomial
 *      to approximate (e^r - 1) with sub-ULP accuracy (60 bits,
 *      8-bit margin for double). Since c0=0 and c1=1, factoring
 *      out r saves one FMA (POLY_EVAL_4 macro with FMA):
 *        q = r * (1 + C2*r + C3*r^2 + C4*r^3 + C5*r^4)
 *
 * 4. Reconstruction:
 *        e^x = (2^m) * (2^(j/64)) * e^r
 *
 *      head + tail is a double-double approximation of 2^(j/64)
 *      with ~106 bits of precision. Since |tail| ≈ 2^-53 * |head|
 *      and |poly| ≈ 0.005, tail*poly ≈ 2^-61 (~0.0003 ULPs) is
 *      negligible, and the reconstruction simplifies to 1 FMA + 1 ADD:
 *        inner = fma(head, poly, tail)   // head*poly + tail
 *        q     = head + inner            // head*(1+poly) + tail
 *      Then 2^m is applied by adding m's exponent bits directly
 *      to the IEEE 754 representation of q.
 */


#include <stdint.h>
#include <emmintrin.h>

#include <libm_util_amd.h>
#include <libm/alm_special.h>
#include <libm_macros.h>
#include <libm/types.h>
#include <libm/typehelper.h>
#include <libm/typehelper-vec.h>
#include <libm/compiler.h>
#include <libm/amd_funcs_internal.h>

#include <libm/poly-vec.h>

#include "../vrd2_exp_kernel.h"

/*
 * Asymmetric fast-path bounds (signed double comparison).
 * Positive limit: largest x with finite exp(x) (overflow boundary).
 * Negative limit: most negative x with exp(x) >= DBL_MIN (denormal boundary,
 * -1022*ln(2)).  NaN is caught by the negated-range idiom below.
 */
#define EXP_MAX_POS   0x1.62e42fefa39efp+9   /* 709.7827...: overflow boundary */
#define EXP_MIN_NEG  (-0x1.6232bdd7abcd2p+9)  /* -708.3964...: denormal boundary */

#define FMIN_X        -0x1.74910d52d3051p+9   /* -745.13: full underflow to zero */
#define DENORMAL_LOW  -0x1.74046dfefd9d0p+9   /* -744.04: boundary for denormal result */
#define DENORMAL_MIN   0x0000000000000001ULL   /* smallest positive denormal */

#define SCALAR_EXP ALM_PROTO_OPT(exp)

v_f64x2_t
ALM_PROTO_OPT(vrd2_exp)(v_f64x2_t x)
{
    /* Branch-free, domain-check-free reconstruction */
    v_f64x2_t ret = vrd2_exp_fastpath(x);

    for(int i = 0; i < 2; i++)
    {
        if(unlikely(!(x[i] <= EXP_MAX_POS && x[i] >= EXP_MIN_NEG))) {
            if (x[i] <= FMIN_X)
                ret[i] = 0.0;
            else if (x[i] <= DENORMAL_LOW)
                ret[i] = asdouble(DENORMAL_MIN);
            else
                ret[i] = SCALAR_EXP(x[i]);
        }
    }

    return ret;
}
