/*
 * Copyright (C) 2019-2026, Advanced Micro Devices. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

/*
 * C implementation of exp double precision 128-bit vector version (v2d)
 *
 * Signature:
 *   v_f64x2_t vrd2_exp(v_f64x2_t x)
 *
 * Algorithm: Table-based range reduction with 64-entry table + degree-5 polynomial
 *
 *   Range reduction and reconstruction follow the scalar exp() fast path
 *   (src/optimized/exp.c), with Sollya-minimax coefficients tuned for vrd2_exp.
 *
 * Implementation Notes
 * ----------------------
 *
 * 1. Argument Reduction:
 *      e^x = 2^(x/ln2) = 2^(x*(64/ln(2))/64)           --- (1)
 *
 *      Choose 'n' and 'f', such that
 *      x * 64/ln2 = n + f                                --- (2)
 *                                     where n is integer, |f| <= 0.5
 *
 *      Choose 'm' and 'j' such that,
 *      n = (64 * m) + j                                  --- (3)
 *                                     where 0 <= j < 64
 *
 *      From (1), (2) and (3),
 *      e^x = 2^((64*m + j + f)/64)
 *          = (2^m) * (2^(j/64)) * 2^(f/64)
 *          = (2^m) * (2^(j/64)) * e^(f*(ln(2)/64))
 *
 * 2. Table Lookup:
 *      Values of (2^(j/64)) are precomputed for j = 0, 1, 2 ... 63,
 *      stored as {head, tail} double-double pairs (~106-bit precision):
 *        head = double(2^(j/64))         — best 53-bit approximation
 *        tail = double(2^(j/64) - head)  — error term (bits 54-106)
 *      Table data: src/optimized/data/_exp_tbl_64_2field.data
 *      Generated by: tools/sollya/gen_exp_tbl_2field.sollya
 *
 * 3. Polynomial Evaluation:
 *      From (2),
 *        f = x*(64/ln(2)) - n
 *      Let,
 *        r = f*(ln(2)/64) = x - n*(ln(2)/64)
 *
 *      Since |f| <= 0.5, we have |r| <= ln(2)/128 ≈ 0.0054.
 *      This narrow range allows a degree-5 Sollya minimax polynomial
 *      to approximate (e^r - 1) with sub-ULP accuracy (60 bits,
 *      8-bit margin for double). Since c0=0 and c1=1, factoring
 *      out r saves one FMA (POLY_EVAL_4 macro with FMA):
 *        q = r * (1 + C2*r + C3*r^2 + C4*r^3 + C5*r^4)
 *
 * 4. Reconstruction:
 *        e^x = (2^m) * (2^(j/64)) * e^r
 *
 *      head + tail is a double-double approximation of 2^(j/64)
 *      with ~106 bits of precision. Since |tail| ≈ 2^-53 * |head|
 *      and |poly| ≈ 0.005, tail*poly ≈ 2^-61 (~0.0003 ULPs) is
 *      negligible, and the reconstruction simplifies to 1 FMA + 1 ADD:
 *        inner = fma(head, poly, tail)   // head*poly + tail
 *        q     = head + inner            // head*(1+poly) + tail
 *      Then 2^m is applied by adding m's exponent bits directly
 *      to the IEEE 754 representation of q.
 */


#include <stdint.h>
#include <emmintrin.h>

#include <libm_util_amd.h>
#include <libm/alm_special.h>
#include <libm_macros.h>
#include <libm/types.h>
#include <libm/typehelper.h>
#include <libm/typehelper-vec.h>
#include <libm/compiler.h>
#include <libm/amd_funcs_internal.h>

#include <libm/poly-vec.h>

#define EXP_TBL_N          6
#define EXP_TBL_SIZE       (1 << EXP_TBL_N)
#define EXP_TBL_MASK       (EXP_TBL_SIZE - 1)

struct vrd2_exp_tbl_entry {
    double head, tail;
};

static const struct {
    v_f64x2_t tblsz_byln2;
    v_f64x2_t ln2_by_tblsz_head, ln2_by_tblsz_tail;
    v_f64x2_t Huge;
    v_f64x2_t poly[4];
    struct vrd2_exp_tbl_entry table[EXP_TBL_SIZE];
    } exp_v2_data = {
        .tblsz_byln2       = _MM_SET1_PD2(0x1.71547652b82fep+6),
        .ln2_by_tblsz_head = _MM_SET1_PD2(-0x1.62e42fefa0000p-7),
        .ln2_by_tblsz_tail = _MM_SET1_PD2(-0x1.cf79abc9e3b39p-46),
        .Huge               = _MM_SET1_PD2(0x1.8000000000000p+52),
        /*
         * Sollya minimax coefficients c2..c5 for degree-5 polynomial:
         *   exp(r) ≈ 1 + r + c2*r^2 + c3*r^3 + c4*r^4 + c5*r^5
         * over [-ln(2)/128, +ln(2)/128]. Runtime evaluates via
         * r * POLY_EVAL_4(r, 1, c2, c3, c4, c5) for (exp(r) - 1).
         * Generated by: tools/sollya/vrd2_exp_table.sollya
         */
        .poly               = {
            _MM_SET1_PD2(0x1.fffffffffdbd9p-2),   /* c2 (Sollya minimax) */
            _MM_SET1_PD2(0x1.5555555557676p-3),   /* c3 (Sollya minimax) */
            _MM_SET1_PD2(0x1.555573c318398p-5),   /* c4 (Sollya minimax) */
            _MM_SET1_PD2(0x1.111108f3731afp-7),   /* c5 (Sollya minimax) */
        },
        .table = {
#include "../data/_exp_tbl_64_2field.data"
        },
    };

#define TBLSZ_BYLN2     exp_v2_data.tblsz_byln2
#define LN2_HEAD         exp_v2_data.ln2_by_tblsz_head
#define LN2_TAIL         exp_v2_data.ln2_by_tblsz_tail
#define EXP_HUGE         exp_v2_data.Huge

#define C2  exp_v2_data.poly[0]
#define C3  exp_v2_data.poly[1]
#define C4  exp_v2_data.poly[2]
#define C5  exp_v2_data.poly[3]

#define EXP_TABLE        exp_v2_data.table

/*
 * Asymmetric fast-path bounds (signed double comparison).
 * Positive limit: largest x with finite exp(x) (overflow boundary).
 * Negative limit: most negative x with exp(x) >= DBL_MIN (denormal boundary,
 * -1022*ln(2)).  NaN is caught by the negated-range idiom below.
 */
#define EXP_MAX_POS   0x1.62e42fefa39efp+9   /* 709.7827...: overflow boundary */
#define EXP_MIN_NEG  (-0x1.6232bdd7abcd2p+9)  /* -708.3964...: denormal boundary */

#define FMIN_X        -0x1.74910d52d3051p+9   /* -745.13: full underflow to zero */
#define DENORMAL_LOW  -0x1.74046dfefd9d0p+9   /* -744.04: boundary for denormal result */
#define DENORMAL_MIN   0x0000000000000001ULL   /* smallest positive denormal */

#define SCALAR_EXP ALM_PROTO_OPT(exp)

v_f64x2_t
ALM_PROTO_OPT(vrd2_exp)(v_f64x2_t x)
{
    /* x * (64/ln2) */
    v_f64x2_t z = x * TBLSZ_BYLN2;

    v_f64x2_t dn = z + EXP_HUGE;

    v_i64x2_t n = as_v2_i64_f64(dn);

    dn = dn - EXP_HUGE;

    /*
     * r = x - dn * (ln2/64), split into head+tail for precision.
     * Range of r: |r| <= ln(2)/128 ≈ 0.0054
     */
    v_f64x2_t r = x + dn * LN2_HEAD;
    r = r + dn * LN2_TAIL;

    /* j = n & 63 (table index), vector bitwise AND */
    v_i64x2_t tbl_mask = _MM_SET1_I64x2(EXP_TBL_MASK);
    v_i64x2_t j = n & tbl_mask;

    /* m = (n - j) << 46: 2^m as IEEE 754 exponent bits (unsigned shift) */
    v_i64x2_t m = (v_i64x2_t)((v_u64x2_t)(n - j) << (52 - EXP_TBL_N));

    /*
     * Table lookup: extract scalar indices and pack into vectors.
     * SSE2 has no gather instruction, so we extract indices, load scalars,
     * and combine via vector literal syntax (v_f64x2_t){low, high}.
     */
    int64_t j0 = j[0], j1 = j[1];
    v_f64x2_t t_head = (v_f64x2_t){EXP_TABLE[j0].head, EXP_TABLE[j1].head};
    v_f64x2_t t_tail = (v_f64x2_t){EXP_TABLE[j0].tail, EXP_TABLE[j1].tail};

    /*
     * Degree-5 Sollya minimax polynomial for e^r - 1:
     *   q = r * (1 + c2*r + c3*r^2 + c4*r^3 + c5*r^4)
     *     = r * POLY_EVAL_4(r, 1, c2, c3, c4, c5)
     * Since c0=0 and c1=1, factoring out r saves one FMA.
     * Coefficients from fpminimax over [-ln(2)/128, ln(2)/128].
     */
    v_f64x2_t poly = r * POLY_EVAL_4(r, _MM_SET1_PD2(1.0), C2, C3, C4, C5);

    /* Reconstruction: head + fma(head, poly, tail)
     * head + tail is a double-double representation of 2^(j/64)
     * with ~106 bits of precision. Since |tail| ≈ 2^-53 * |head|
     * and |poly| ≈ 0.005, tail*poly ≈ 2^-61 which is sub-ULP.
     */
    v_f64x2_t inner = mul_add(t_head, poly, t_tail);
    v_f64x2_t q_result = t_head + inner;

    /* Apply 2^m by adding exponent bits to IEEE 754 representation */
    v_f64x2_t ret = as_v2_f64_u64(as_v2_u64_f64(q_result) + (v_u64x2_t)m);

    for(int i = 0; i < 2; i++)
    {
        if(unlikely(!(x[i] <= EXP_MAX_POS && x[i] >= EXP_MIN_NEG))) {
            if (x[i] <= FMIN_X)
                ret[i] = 0.0;
            else if (x[i] <= DENORMAL_LOW)
                ret[i] = asdouble(DENORMAL_MIN);
            else
                ret[i] = SCALAR_EXP(x[i]);
        }
    }

    return ret;
}
