- test_sequence: perf_tests
  function: fabs
  timing_enabled: true
  test_sets:
  - id: fabs
    tests:
# Single Precision
    - id: fabs_001
      description: 'Positive values: x in [SMALLEST_SUBNORMAL, FLT_MAX], linearstep'
      input: [[min_subnormal, max]]
      type: [linearstep]
      steps: [10000]
      variants : [ss, vrs4, vrs8, vrsa]
    - id: fabs_002
      description: 'x in [[-min_subnormal, min_subnormal]], linearstep'
      input: [[-min_subnormal, min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants : [ss, vrs4, vrs8, vrsa]
    - id: fabs_003
      description: 'Negative values: x in [-FLT_MAX, -SMALLEST_SUBNORMAL], linearstep'
      input: [[-max, -min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants : [ss, vrs4, vrs8, vrsa]

#Double precision
    - id: fabs_001
      description: 'Positive values: x in [SMALLEST_SUBNORMAL, DBL_MAX], linearstep'
      input: [[min_subnormal, max]]
      type: [linearstep]
      steps: [10000]
      variants : [sd, vrd2, vrd4, vrda]
    - id: fabs_002
      description: 'x in [[-min_subnormal, min_subnormal]], linearstep'
      input: [[-min_subnormal, min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants : [sd, vrd2, vrd4, vrda]
    - id: fabs_003
      description: 'Negative values: x in [-DBL_MAX, -SMALLEST_SUBNORMAL], linearstep'
      input: [[-max, -min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants : [sd, vrd2, vrd4, vrda]
