- test_sequence: validation_tests_fabs
  function: fabs
  test_sets:
  - id: range-tests_01
    tests:
    - id: fabs_001
      description: 'Full value distribution range tests: [-FLT_MAX, -SMALLEST_SUBNORMAL] expstep'
      input:
      - [0xFF7FFFFF, -min_subnormal]
      type: [expstep]
      steps: [10000]
      variants : [ss, vrs4, vrs8, vrsa]

    - id: fabs_002
      description: 'Full value distribution range tests: [+SMALLEST_SUBNORMAL, FLT_MAX] expstep'
      input:
      - [min_subnormal, max]
      type: [expstep]
      steps: [10000]
      variants : [ss, vrs4, vrs8, vrsa]

    - id: fabs_003
      description: 'Subnormal values range tests: [-LARGEST_SUBNORMAL, +LARGEST_SUBNORMAL] linearstep'
      input:
      - [-max_subnormal, max_subnormal]
      type: [linearstep]
      steps: [2000]
      variants : [ss, vrs4, vrs8, vrsa]

    - id: fabs_004
      description: Test around 0, negative values
      input:
      - [0x80000000, 0x80000FFF]
      type: [bitstep]
      steps: [1]
      variants : [ss, vrs4, vrs8, vrsa]

    - id: fabs_005
      description: Test around 0, positive values
      input:
      - [0.0, 0x00000FFF]
      type: [bitstep]
      steps: [1]
      variants : [ss, vrs4, vrs8, vrsa]

    - id: fabs_006
      description: Test around -LARGEST_SUBNORMAL
      input:
      - [0x807fff00, 0x808000FF]
      type: [bitstep]
      steps: [1]
      variants : [ss, vrs4, vrs8, vrsa]

    - id: fabs_007
      description: Test around +LARGEST_SUBNORMAL
      input:
      - [0x007fff00, 0x008000ff]
      type: [bitstep]
      steps: [1]
      variants : [ss, vrs4, vrs8, vrsa]

#Double precision
    - id: fabs_001
      description: 'Full value distribution range tests: [-DBL-MAX, -SMALLEST_SUBNORMAL] expstep'
      input:
      - [0xFFeFFFFFFFFFFFFF, -min_subnormal]
      type: [expstep]
      steps: [10000]
      variants : [sd, vrd2, vrd4, vrda]

    - id: fabs_002
      description: 'Full value distribution range tests: [+SMALLEST_SUBNORMAL, DBL-MAX] expstep'
      input:
      - [min_subnormal, max]
      type: [expstep]
      steps: [10000]
      variants : [sd, vrd2, vrd4, vrda]

    - id: fabs_003
      description: 'Subnormal values range tests: [-LARGEST_SUBNORMAL, +LARGEST_SUBNORMAL] linearstep'
      input:
      - [0x800FFFFFFFFFFFFF, 0x000FFFFFFFFFFFFF]
      type: [linearstep]
      steps: [2000]
      variants : [sd, vrd2, vrd4, vrda]

    - id: fabs_004
      description: Test around 0, negative values
      input:
      - [-0.0, 0x8000000000000FFF]
      type: [bitstep]
      steps: [1]
      variants : [sd, vrd2, vrd4, vrda]

    - id: fabs_005
      description: Test around 0, positive values
      input:
      - [0.0, 0x0000000000000FFF]
      type: [bitstep]
      steps: [1]
      variants : [sd, vrd2, vrd4, vrda]

    - id: fabs_006
      description: Test around -LARGEST_SUBNORMAL
      input:
      - [0x800FFFFFFFFFFF00, 0x80100000000000FF]
      type: [bitstep]
      steps: [1]
      variants : [sd, vrd2, vrd4, vrda]

    - id: fabs_007
      description: Test around +LARGEST_SUBNORMAL
      input:
      - [0x000FFFFFFFFFFF00, 0x00100000000000FF]
      type: [bitstep]
      steps: [1]
      variants : [sd, vrd2, vrd4, vrda]

