/*
 * Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software without
 *    specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
 * OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

/*
 * Single definition of the 64-entry double-double 2^(j/64) table declared
 * (extern) in ../vrd2_exp_kernel.h.  The kernel header is included by
 * multiple translation units (vrd2_exp.c, vrd2_cosh.c, ...) that are in turn
 * compiled once per micro-architecture, so an in-header (or in-vec-source)
 * definition would emit one copy of the ~1KB table per (TU x arch) pair.
 * This file lives under src/optimized/data/ and is compiled exactly once by
 * the "opt" target, giving the table a single shared definition.  Placing it
 * beside the generated data also makes the include path self-contained (no
 * reliance on src/optimized being on the header search path).
 *
 *   head = double(2^(j/64))          (best 53-bit approximation)
 *   tail = double(2^(j/64) - head)   (error term, bits 54-106)
 * Generated by: tools/sollya/gen_exp_tbl_2field.sollya
 */

#include "../vrd2_exp_kernel.h"

const struct vrd2_exp_kernel_tbl_entry
    v2_exp_kernel_table[VRD2_EXP_KERNEL_TBL_SIZE] HIDDEN = {
#include "_exp_tbl_64_2field.data"
};
