# Copyright (C) 2018, AMD. All rights Reserved
#
# Author: Prem Mallappa <pmallapp@amd.com>

Import('env')

e = env.Clone()

#e.Append( LIBS = ['test'] )

log_srcs = Glob('*.[cS]')

#exp2 = e.Program('test_exp2', exp2_srcs, LIBS=liblist, LIBPATH=libpath)
log = e.Program('test_log', log_srcs)

Return('log')

