#
# Copyright (C) 2008-2022 Advanced Micro Devices, Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Inherit global environment
Import('env')
import os
from os.path import join as joinpath
from os.path import dirname,isdir

builddir = joinpath(env['BUILDROOT'], 'src', 'arch')

e = env.Clone()

if '-ffast-math' in e['CFLAGS']:
    e['CFLAGS'].remove('-ffast-math')

incpaths = [
    '#' + joinpath(Dir('.').srcnode().path),
    '#' + joinpath(Dir('.').srcnode().path, 'include')
]

e.Append(
    CPPPATH = incpaths
)

objs = []

dirs = ['zen', 'zen2', 'zen3', 'zen4']

for d in dirs:
    aenv = e.Clone()
    sdir = joinpath(aenv['CWD'], d)
    aenv.Append(
        CWD = sdir
    )
    objs += SConscript('%s/SConscript'%d,
                       exports = { 'env': aenv },
                       duplicate = 0,
                       src_dir = sdir,
                       variant_dir = joinpath(builddir, d)
    )

Return('objs')
