# Copyright (C) 2008-2020 Advanced Micro Devices, Inc. All rights reserved.
#

# Inherit global environment
Import('env')
from os.path import join as joinpath

builddir = joinpath(env['BUILDROOT'], 'src', 'optmized')

e = env.Clone()

# These rearrangements are not value-safe:
#	 (a ⊕ b) ⊕ c ⇒ a ⊕ (b ⊕ c)
#	 a ⊗ (b ⊕ c) ⇒ (a ⊗ b) ⊕ (a ⊕ c)
# 
# To Disallow these changes in gcc remove -ffast-math
if '-ffast-math' in e['CFLAGS']:
    e['CFLAGS'].remove('-ffast-math')

incpaths = [
    '#' + joinpath(Dir('.').srcnode().path),
    '#' + joinpath(Dir('.').srcnode().path, 'include')
]

e.MergeFlags({
    'CFLAGS'  : ['-march=znver3', '-O3', '-fPIC', '-flax-vector-conversions'],
    'CPPPATH' : incpaths
})

experimental_src = []

source = Glob('*.c', exclude=experimental_src)
#source = Glob('*.c')

objs = e.StaticObject(source)

Return('objs')
