# Copyright (C) 2018, AMD. All rights Reserved
#
# Author: Prem Mallappa <pmallapp@amd.com>

Import('env')

e = env.Clone()

#e.Append( LIBS = ['test'] )

exp_srcs = Glob('*.[cS]', exclude='exp_old.c')

#exp = e.Program('test_exp', exp_srcs, LIBS=liblist, LIBPATH=libpath)
exp = e.Program('test_exp', exp_srcs)

Return('exp')

