# Copyright (C) 2018, AMD. All rights Reserved
#
# Author: Prem Mallappa <pmallapp@amd.com>

Import('env')

e = env.Clone()

pow_srcs = Glob('*.[cS]')

pow = e.Program('test_pow', pow_srcs)

Return('pow')

