- test_sequence: perf_tests
  function: acos
  timing_enabled: true
  test_sets:
  - id: acos
    tests:
# Single Precision
    - id: acos_001
      description: 'Positive values: x in [SMALLEST_SUBNORMAL, 1.0], linearstep'
      input: [[min_subnormal, 0x3f800000]]
      type: [linearstep]
      steps: [10000]
      variants: [ss, vrs4, vrs8, vrs16, vrsa]

    - id: acos_002
      description: 'x in [[-min_subnormal, min_subnormal]], linearstep'
      input: [[-min_subnormal, min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants: [ss, vrs4, vrs8, vrs16, vrsa]

    - id: acos_003
      description: 'Negative values: x in [-1.0, -SMALLEST_SUBNORMAL], linearstep'
      input: [[0xbf800000, -min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants: [ss, vrs4, vrs8, vrs16, vrsa]

# double Precision
    - id: acos_001
      description: 'Positive values: x in [SMALLEST_SUBNORMAL, 1.0], linearstep'
      input: [[min_subnormal, 0x3ff0000000000000]]
      type: [linearstep]
      steps: [10000]
      variants : [sd, vrd2, vrd4, vrda]

    - id: acos_002
      description: ' x in [[-min_subnormal, min_subnormal]], linearstep'
      input: [[-min_subnormal, min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants : [sd, vrd2, vrd4, vrda]

    - id: acos_003
      description: 'Negative values: x in [-1.0, -SMALLEST_SUBNORMAL], linearstep'
      input: [[0xbff0000000000000, -min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants : [sd, vrd2, vrd4, vrda]


