
#ifdef __cplusplus
extern "C" {
#endif

float amd_ref_acosf(float x);
float amd_ref_acosf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_acoshf(float x);
float amd_ref_acoshf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_asinf(float x);
float amd_ref_asinf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_asinhf(float x);
float amd_ref_asinhf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_atanf(float x);
float amd_ref_atanf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_atan2f(float x, float y);
float amd_ref_atan2f_ULP(float x, float y,float z, double   *sulps, double   *sreldiff);
float amd_ref_atanhf(float x);
float amd_ref_atanhf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_cbrtf(float x);
float amd_ref_cbrtf_ULP(float x, float z, double   *sulps, double   *sreldiff);
float amd_ref_ceilf(float x);
float amd_ref_ceilf_ULP(float x, float z, double   *sulps, double   *sreldiff);
float amd_ref_copysignf(float x, float y);
float amd_ref_copysignf_ULP(float x, float y,float z,double   *sulps, double   *sreldiff);
float amd_ref_cosf(float x);
float amd_ref_cosf_ULP(float x, float z, double   *sulps, double   *sreldiff);
float amd_ref_coshf(float x);
float amd_ref_coshf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_expf(float x);
float amd_ref_expf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_exp10f(float x);
float amd_ref_exp10f_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_exp2f(float x);
float amd_ref_exp2f_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_expm1f(float x);
float amd_ref_expm1f_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_fabsf(float x);
float amd_ref_fabsf_ULP(float x, float z, double   *sulps, double   *sreldiff);
float amd_ref_fdimf(float x, float y);
float amd_ref_fdimf_ULP(float x, float y,float z, double   *sulps, double   *sreldiff);
int amd_ref_finitef(float x);
int amd_ref_finitef_ULP(float x, int z, double   *sulps, double   *sreldiff);
float amd_ref_floorf(float x);
float amd_ref_floorf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_fmaf(float x, float y, float z);
float amd_ref_fmaf_ULP(float x, float y, float z,float re, double   *sulps, double   *sreldiff);
float amd_ref_fmaxf(float x, float y);
float amd_ref_fmaxf_ULP(float x, float y,float z, double   *sulps, double   *sreldiff);
float amd_ref_fminf(float x, float y);
float amd_ref_fminf_ULP(float x, float y,float z, double   *sulps, double   *sreldiff);
float amd_ref_fmodf(float x, float y);
float amd_ref_fmodf_ULP(float x, float y,float z, double   *sulps, double   *sreldiff);
float amd_ref_frexpf(float x, int *ptr);
float amd_ref_frexpf_ULP(float x, int *ptr, float z, double *sulps, double *sreldiff);
float amd_ref_hypotf(float x, float y);
float amd_ref_hypotf_ULP(float x, float y,float z, double   *sulps, double   *sreldiff);
int amd_ref_ilogbf(float x);
int amd_ref_ilogbf_ULP(float x, int z, double   *sulps, double   *sreldiff);
float amd_ref_ldexpf(float x, int expn);
float amd_ref_ldexpf_ULP(float x, int expn, float z, double *sulps, double *sreldiff);
float amd_ref_logf(float x);
float amd_ref_logf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_log10f(float x);
float amd_ref_log10f_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_log1pf(float x);
float amd_ref_log1pf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_log2f(float x);
float amd_ref_log2f_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_logbf(float x);
float amd_ref_logbf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_modff(float x, float *ptr);
float amd_ref_modff_ULP(float x, float *ptr, float z, double   *sulps, double   *sreldiff);
float amd_ref_powf(float x, float y);
float amd_ref_powf_ULP(float x, float y,float z, double   *sulps, double   *sreldiff);
float amd_ref_remainderf(float x, float y);
float amd_ref_remainderf_ULP(float x, float y,float z, double   *sulps, double   *sreldiff);
float amd_ref_remquof(float x, float y, int* quotient);
float amd_ref_remquof_ULP(float x, float y, int* quotient, float z, double * sulps, double *sreldiff);
float amd_ref_rintf(float x);
float amd_ref_rintf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_roundf(float x);
float amd_ref_roundf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_sinf(float x);
float amd_ref_sinf_ULP(float x,float z, double   *sulps, double   *sreldiff);
void amd_ref_sincosf(float x, float *s, float *c);
void amd_ref_sincosf_ULP(float x, float s, float c,float co, double   *sulps, double   *sreldiff);
float amd_ref_sinhf(float x);
float amd_ref_sinhf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_sqrtf(float x);
float amd_ref_sqrtf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_tanf(float x);
float amd_ref_tanf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_tanhf(float x);
float amd_ref_tanhf_ULP(float x,float z, double   *sulps, double   *sreldiff);
float amd_ref_truncf(float x);
float amd_ref_truncf_ULP(float x,float z,double   *sulps, double   *sreldiff);




double amd_ref_acos(double x);
double amd_ref_acos_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_acosh(double x);
double amd_ref_acosh_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_asin(double x);
double amd_ref_asin_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_asinh(double x);
double amd_ref_asinh_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_atan(double x);
double amd_ref_atan_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_atan2(double x, double y);
double amd_ref_atan2_ULP(double x, double y,double z, double   *sulps, double   *sreldiff);
double amd_ref_atanh(double x);
double amd_ref_atanh_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_cbrt(double x);
double amd_ref_cbrt_ULP(double x, double z, double   *sulps, double   *sreldiff);
double amd_ref_ceil(double x);
double amd_ref_ceil_ULP(double x, double z, double   *sulps, double   *sreldiff);
double amd_ref_copysign(double x, double y);
double amd_ref_copysign_ULP(double x, double y,double z,double   *sulps, double   *sreldiff);
double amd_ref_cos(double x);
double amd_ref_cos_ULP(double x, double z, double   *sulps, double   *sreldiff);
double amd_ref_cosh(double x);
double amd_ref_cosh_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_exp(double x);
double amd_ref_exp_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_exp10(double x);
double amd_ref_exp10_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_exp2(double x);
double amd_ref_exp2_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_expm1(double x);
double amd_ref_expm1_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_fabs(double x);
double amd_ref_fabs_ULP(double x, double z, double   *sulps, double   *sreldiff);
double amd_ref_fdim(double x, double y);
double amd_ref_fdim_ULP(double x, double y,double z, double   *sulps, double   *sreldiff);
int amd_ref_finite(double x);
int amd_ref_finite_ULP(double x, int z, double   *sulps, double   *sreldiff);
double amd_ref_floor(double x);
double amd_ref_floor_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_fma(double x, double y, double z);
double amd_ref_fma_ULP(double x, double y, double z,double re, double   *sulps, double   *sreldiff);
double amd_ref_fmax(double x, double y);
double amd_ref_fmax_ULP(double x, double y,double z, double   *sulps, double   *sreldiff);
double amd_ref_fmin(double x, double y);
double amd_ref_fmin_ULP(double x, double y,double z, double   *sulps, double   *sreldiff);
double amd_ref_fmod(double x, double y);
double amd_ref_fmod_ULP(double x, double y,double z, double   *sulps, double   *sreldiff);
double amd_ref_frexp(double x, int *ptr);
double amd_ref_frexp_ULP(double x, int *ptr, double z, double *sulps, double *sreldiff);
double amd_ref_hypot(double x, double y);
double amd_ref_hypot_ULP(double x, double y,double z, double   *sulps, double   *sreldiff);
int amd_ref_ilogb(double x);
int amd_ref_ilogb_ULP(double x, int z, double   *sulps, double   *sreldiff);
double amd_ref_ldexp(double x, int expn);
double amd_ref_ldexp_ULP(double x, int expn, double z, double *sulps, double *sreldiff);
double amd_ref_log(double x);
double amd_ref_log_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_log10(double x);
double amd_ref_log10_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_log1p(double x);
double amd_ref_log1p_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_log2(double x);
double amd_ref_log2_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_logb(double x);
double amd_ref_logb_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_modf(double x, double *ptr);
double amd_ref_modf_ULP(double x, double *ptr, double z, double   *sulps, double   *sreldiff);
double amd_ref_pow(double x, double y);
double amd_ref_pow_ULP(double x, double y,double z, double   *sulps, double   *sreldiff);
double amd_ref_remainder(double x, double y);
double amd_ref_remainder_ULP(double x, double y,double z, double   *sulps, double   *sreldiff);
double amd_ref_remquo(double x, double y, int* quotient);
double amd_ref_remquo_ULP(double x, double y, int* quotient, double z, double * sulps, double *sreldiff);
double amd_ref_rint(double x);
double amd_ref_rint_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_round(double x);
double amd_ref_round_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_sin(double x);
double amd_ref_sin_ULP(double x,double z, double   *sulps, double   *sreldiff);
void amd_ref_sincos(double x, double *s, double *c);
void amd_ref_sincos_ULP(double x, double s, double c,double   *sulps, double   *sreldiff);
double amd_ref_sinh(double x);
double amd_ref_sinh_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_sqrt(double x);
double amd_ref_sqrt_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_tan(double x);
double amd_ref_tan_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_tanh(double x);
double amd_ref_tanh_ULP(double x,double z, double   *sulps, double   *sreldiff);
double amd_ref_trunc(double x);
double amd_ref_trunc_ULP(double x,double z,double   *sulps, double   *sreldiff);


double amd_ref_tanpi(double x);
double amd_ref_tanpi_ULP(double x,double z, double   *sulps, double   *sreldiff);


#ifdef __cplusplus
}
#endif

