# Inherit global environment
Import('env')

e = env.Clone()

e.Append(
    CFLAGS = ['-fPIC']
)

try:
    if not env['debug_mode']:
        e.Append(
            CCFLAGS = ['-O3'],
        )
except KeyError as err:
    print("Keyerror, debug_mode not found", err)

#source = Glob('*.c', exclude=['log.c'])
source = Glob('*.c')

objs = e.StaticObject(source)

Return('objs')
