# Copyright (C) 2018, AMD. All rights Reserved
#
# Author: Prem Mallappa <pmallapp@amd.com>

Import('env')

e = env.Clone()

fabs_srcs = Glob('*.[cS]')

fabs = e.Program('test_fabs', fabs_srcs)

Return('fabs')

