#
# Copyright (C) 2019-2020 Advanced Micro Devices, Inc. All rights reserved
#

Import('env')

e = env.Clone()

atanh_srcs = Glob('*.cc')

atanh = e.Program('test_atanh', atanh_srcs)

Return('atanh')

