# Copyright (C) 2018, AMD. All rights Reserved
#

Import('env')

e = env.Clone()

#e.Append( LIBS = ['test'] )

sin_srcs = Glob('*.[cS]', exclude='sin_old.c')

#sin = e.Program('test_sin', sin_srcs, LIBS=liblist, LIBPATH=libpath)
sin = e.Program('test_sin', sin_srcs)

Return('sin')

