- test_sequence: perf_tests
  function: round
  timing_enabled: true
  test_sets:
  - id: range-tests_01
    tests:
# Single Precision
    - id: round_001
      description: 'Positive values: x in [0.001, 10.0e18], linearstep'
      input: [[0.001, 1.0e+19]]
      type: [linearstep]
      steps: [10000]
      variants : [ss]

    - id: round_002
      description: 'x in [-min_subnormal, min_subnormal], linearstep'
      input: [[-min_subnormal, min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants : [ss]

    - id: round_003
      description: 'Negative values: x in [-10.0e18, -0.001], linearstep'
      input: [[-1.0e+19, -0.001]]
      type: [linearstep]
      steps: [10000]
      variants : [ss]

#Double precision
    - id: round_001
      description: 'Positive values: x in [0.001, 10.0e18], linearstep'
      input: [[0.001, 1.0e+19]]
      type: [linearstep]
      steps: [10000]
      variants : [sd]

    - id: round_002
      description: 'x in [-min_subnormal, min_subnormal], linearstep'
      input: [[-min_subnormal, min_subnormal]]
      type: [linearstep]
      steps: [10000]
      variants : [sd]

    - id: round_003
      description: 'Negative values: x in [-10.0e18, -0.001], linearstep'
      input: [[-1.0e+19, -0.001]]
      type: [linearstep]
      steps: [10000]
      variants : [sd]

