#
# Copyright (C) 2024-2026, Advanced Micro Devices. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Inherit global environment
Import('env')
from os.path import join as joinpath

e = env.Clone()

# Inline-asm C sources
avx2_srcs = [
    'fmaf_fma3.c',
    'fma_fma3.c',
    'log_fma3.c',
    'vrs4_cbrtf_fma3.c',
    'vrs4_exp10f_fma3.c',
    'vrs4_expm1f_fma3.c',
    'vrs4_log1pf_fma3.c',
    'vrd2_cbrt_fma3.c',
    'vrd2_exp10_fma3.c',
    'vrd2_log10_fma3.c',
    'vrd2_log1p_fma3.c',
    'vrda_expm1_fma3.c',
]

# Set up include paths
p = joinpath(Dir('.').srcnode().path)
incpaths = [
    '#' + p,
    '#' + joinpath(p, 'include'),
    '#include',
    '#include/libm',
    '#src/isa/include',
]

if e['HOST_OS'] != 'win32':
    # -fcf-protection=none: these naked kernels are direct ports of hand-written
    # asm that had no CET endbr64 landing pad. Dropping the pad matches the asm
    # and avoids a per-call instruction on tiny hot kernels (e.g. vrd2_exp10).
    isa_flags = ['-mavx2', '-mfma', '-O3', '-fPIC', '-flax-vector-conversions',
                 '-fcf-protection=none']
else:
    isa_flags = ['-mavx2', '-mfma', '-O3']

e.Append(
    CPPPATH = incpaths,
    CCFLAGS = isa_flags,
)

# Build inline-asm C objects
objs = e.StaticObject(avx2_srcs)

Return('objs')
