# Copyright (C) 2008-2020 Advanced Micro Devices, Inc. All rights reserved.
#

# Inherit global environment
Import('env')
from os.path import join as joinpath

builddir = joinpath(env['BUILDROOT'], 'src', 'optmized')

e = env.Clone()

p = joinpath(Dir('.').srcnode().path)

incpaths = [
    '#' +  p,
    '#' +  joinpath(p, 'include'),
    '#' +  joinpath(p, 'gas', 'include')

]

e.Append(
    #CFLAGS = ['-O3', '-fPIC', '-flax-vector-conversions'],
    CPPPATH = incpaths
)

experimental_src = []

source = Glob('*.c', exclude=experimental_src)
source += Glob('gas/*.S', exclude=experimental_src)
#source = Glob('*.c')

objs = e.StaticObject(source)

Return('objs')
