# Copyright (C) 2020, AMD. All rights Reserved
#
# Author: Pranoy Jayaraj <pjayaraj@amd.com>

#compile this dynamic loading tests with gcc
Import('env')
e = env.Clone()

test_cflags = ['-g', '-mavx', '-fPIE', '-fpermissive']

#check if avx512 enabled
if e.has_key('arch_config') and e['arch_config'] == 'avx512':
    test_cflags.append('-mavx512f')
    test_cflags.append('-D__AVX512__')

e.Append(
    INCPATH= ['inc'],
    CPPPATH= ['inc'],
    CFLAGS = test_cflags,
    LDFLAGS= ['-fPIE'],
    LIBS   = ['dl', 'm'],
)

srcs = Glob('./src/*.[cS]')

exe = e.Program(source = srcs,
                target = 'test_dynamic')

Return('exe')

