# Copyright (C) 2018, AMD. All rights Reserved
#
# Author: Prem Mallappa <pmallapp@amd.com>

Import('env')

e = env.Clone()

atan_srcs = Glob('*.[cS]')

atan = e.Program('test_atan', atan_srcs)

Return('atan')

