#ifndef __WINNAG_H__
#define __WINNAG_H__

#define amd_ref_acosf		acosf
#define amd_ref_acoshf		acoshf
#define amd_ref_asinf		asinf
#define amd_ref_asinhf		asinhf
#define amd_ref_atanf		atanf
#define amd_ref_atan2f		atan2f
#define amd_ref_atanhf		atanhf
#define amd_ref_cbrtf		cbrtf
#define amd_ref_ceilf		ceilf
#define amd_ref_copysign	copysign
#define amd_ref_cosf		cosf
#define amd_ref_coshf		coshf
#define amd_ref_expf		expf
#define amd_ref_exp10f		exp10f
#define amd_ref_exp2f		exp2f
#define amd_ref_expm1f		expm1f
#define amd_ref_fabsf		fabsf
#define amd_ref_fdimf		fdimf
#define amd_ref_finitef		finitef
#define amd_ref_floorf		floorf
#define amd_ref_fmaf		fmaf
#define amd_ref_fmaxf		fmaxf
#define amd_ref_fminf		fminf
#define amd_ref_fmodf		fmodf
#define amd_ref_frexpf		frexpf
#define amd_ref_hypotf		hypotf
#define amd_ref_ilogbf		ilogbf
#define amd_ref_ldexpf		ldexpf
#define amd_ref_logf		logf
#define amd_ref_log10f		log10f
#define amd_ref_log1pf		log1pf
#define amd_ref_log2f		log2f
#define amd_ref_logbf		logbf
#define amd_ref_modff		modff
#define amd_ref_powf		powf
#define amd_ref_remainde	remainde
#define amd_ref_remquof		remquof
#define amd_ref_rintf		rintf
#define amd_ref_roundf		roundf
#define amd_ref_sinf		sinf
#define amd_ref_sincosf		sincosf
#define amd_ref_sinhf		sinhf
#define amd_ref_sqrtf		sqrtf
#define amd_ref_tanf		tanf
#define amd_ref_tanhf		tanhf
#define amd_ref_truncf		truncf
#define amd_ref_acos		acos
#define amd_ref_acosh		acosh
#define amd_ref_asin		asin
#define amd_ref_asinh		asinh
#define amd_ref_atan		atan
#define amd_ref_atan2		atan2
#define amd_ref_atanh		atanh
#define amd_ref_cbrt		cbrt
#define amd_ref_ceil		ceil
#define amd_ref_copysign	copysign
#define amd_ref_cos			cos
#define amd_ref_cosh		cosh
#define amd_ref_exp			exp
#define amd_ref_exp10		exp10
#define amd_ref_exp2		exp2
#define amd_ref_expm1		expm1
#define amd_ref_fabs		fabs
#define amd_ref_fdim		fdim
#define amd_ref_finite		finite
#define amd_ref_floor		floor
#define amd_ref_fma			fma
#define amd_ref_fmax		fmax
#define amd_ref_fmin		fmin
#define amd_ref_fmod		fmod
#define amd_ref_frexp		frexp
#define amd_ref_hypot		hypot
#define amd_ref_ilogb		ilogb
#define amd_ref_ldexp		ldexp
#define amd_ref_log			log
#define amd_ref_log10		log10
#define amd_ref_log1p		log1p
#define amd_ref_log2		log2
#define amd_ref_logb		logb
#define amd_ref_modf		modf
#define amd_ref_pow			pow
#define amd_ref_remainder	remainder
#define amd_ref_remquo		remquo
#define amd_ref_rint		rint
#define amd_ref_round		round
#define amd_ref_sin			sin
#define amd_ref_sincos		sincos
#define amd_ref_sinh		sinh
#define amd_ref_sqrt		sqrt
#define amd_ref_tan			tan
#define amd_ref_tanh		tanh
#define amd_ref_trunc		trunc


#endif //__WINNAG_H__