---
- test_sequence: validation_tests_atanh
  function: atanh
  test_sets:
  - id: range-tests_01
    description: 'Full value distribution range tests0'
    tests:
    - id: atanh_001
      description: '[+SMALLEST_SUBNORMAL, +1.0] expstep'
      input:
      - [min_subnormal, 0x3f800000]
      type: [expstep]
      steps: [10000]
      variants : [ss]

    - id: atanh_002
      description: '[-1.0, -SMALLEST_SUBNORMAL] expstep'
      input:
      - [0xbf800000, -min_subnormal]
      type: [expstep]
      steps: [10000]
      variants : [ss]

  - id: subnormal-range
    description: 'Subnormal values range tests0'
    tests:
    - id: atanh_003
      description: '[0, LARGEST_SUBNORMAL] linearstep'
      input:
      - [0.0, max_subnormal]
      type: [linearstep]
      steps: [5000]
      variants : [ss]

    - id: atanh_004
      description: '[-LARGEST_SUBNORMAL, -0] linearstep'
      input:
      - [-max_subnormal, -0.0]
      type: [linearstep]
      steps: [5000]
      variants : [ss]

    - id: atanh_005
      description: 'Test around positive 0'
      input:
      - [0.0, 0x00000fff]
      type: [bitstep]
      steps: [1]
      variants : [ss]

    - id: atanh_006
      description: 'Test around negative 0'
      input:
      - [0x80000000, 0x80000fff]
      type: [bitstep]
      steps: [1]
      variants : [ss]

    - id: atanh_007
      description: 'Test around LARGEST_SUBNORMAL'
      input:
      - [0x007ff000, 0x00800fff]
      type: [bitstep]
      steps: [1]
      variants : [ss]

    - id: atanh_008
      description: 'Test around -LARGEST_SUBNORMAL'
      input:
      - [0x807ff000, 0x80800fff]
      type: [bitstep]
      steps: [1]
      variants : [ss]

    - id: atanh_009
      description: 'Test around +1.0'
      input:
      - [0x3f7ff000, 0x3f800000]
      type: [bitstep]
      steps: [1]
      variants : [ss]

    - id: atanh_010
      description: 'Test around -1.0'
      input:
      - [0xbf7ff000, 0xbf800000]
      type: [bitstep]
      steps: [1]
      variants : [ss]

  #Double precision
  - id: range-tests_01
    description: 'Full value distribution range tests'
    tests:
    - id: atanh_001
      description: '[+SMALLEST_SUBNORMAL, +1.0] expstep'
      input:
      - [min_subnormal, 0x3ff0000000000000]
      type: [expstep]
      steps: [10000]
      variants : [sd]

    - id: atanh_002
      description: '[-1.0, -SMALLEST_SUBNORMAL] expstep'
      input:
      - [0xbff0000000000000, -min_subnormal]
      type: [expstep]
      steps: [10000]
      variants : [sd]

  - id: subnormal-range
    description: 'Subnormal values range tests'
    tests:
    - id: atanh_003
      description: '[0, LARGEST_SUBNORMAL] linearstep'
      input:
      - [0.0, max_subnormal]
      type: [linearstep]
      steps: [5000]
      variants : [sd]

    - id: atanh_004
      description: '[-LARGEST_SUBNORMAL, -0] linearstep'
      input:
      - [-max_subnormal, -0.0]
      type: [linearstep]
      steps: [5000]
      variants : [sd]

    - id: atanh_005
      description: 'Test around positive 0'
      input:
      - [0.0, 0x0000000000000fff]
      type: [bitstep]
      steps: [1]
      variants : [sd]

    - id: atanh_006
      description: 'Test around negative 0'
      input:
      - [0x8000000000000000, 0x8000000000000fff]
      type: [bitstep]
      steps: [1]
      variants : [sd]

    - id: atanh_007
      description: 'Test around LARGEST_SUBNORMAL'
      input:
      - [0x000ffffffffff000, 0x0010000000000fff]
      type: [bitstep]
      steps: [1]
      variants : [sd]

    - id: atanh_008
      description: 'Test around -LARGEST_SUBNORMAL'
      input:
      - [0x800ffffffffff000, 0x8010000000000fff]
      type: [bitstep]
      steps: [1]
      variants : [sd]

    - id: atanh_009
      description: 'Test around +1.0'
      input:
      - [0x3feffffffffff000, 0x3ff0000000000000]
      type: [bitstep]
      steps: [1]
      variants : [sd]

    - id: atanh_010
      description: 'Test around -1.0'
      input:
      - [0xbfeffffffffff000, 0xbff0000000000000]
      type: [bitstep]
      steps: [1]
      variants : [sd]
