# Copyright (C) 2018, AMD. All rights Reserved
#

Import('env')

e = env.Clone()

#e.Append( LIBS = ['test'] )

cos_srcs = Glob('*.[cS]', exclude='cos_old.c')

#cos = e.Program('test_cos', cos_srcs, LIBS=liblist, LIBPATH=libpath)
cos = e.Program('test_cos', cos_srcs)

Return('cos')

