# Copyright (C) 2018, AMD. All rights Reserved
#

Import('env')

e = env.Clone()

#e.Append( LIBS = ['test'] )

tan_srcs = Glob('*.[cS]', exclude='tan_old.c')

#tan = e.Program('test_tan', tan_srcs, LIBS=liblist, LIBPATH=libpath)
tan = e.Program('test_tan', tan_srcs)

Return('tan')

