# Copyright (C) 2018, AMD. All rights Reserved
#

# Inherit global environment
Import('env')

experimental_src = []

source = Glob('*.c', exclude=experimental_src)
source += Glob('data/*.c', exclude=experimental_src)

objects = env.StaticObject(source)

Return('objects')

