* LIBM Directory Structure

** Skeleton (top level)

- doc - All realtive documentation should go here
- include - All headers relavent for sources
- src - All sources
- tests - All tests
- utils - Any necessary utilities
- scripts - Scripts necessary for building

** Documentation

Mostly recides under 'doc/' folder. 

doc/internal - is internal reference only.

doc/user - User manual, software developers manual etc. Released externally

** Source

Contains following directories

src/
   ref/               - mostly reference implementations.
   isa/avx/           - AVX only source.
   isa/avx/gas/       - Assembly only files for GNU ASsembler (128-bit instructions)
   isa/fma4/          - FMA4 (Buldozer) specific 
   isa/avx/gas/       - FMA4 (Buildozer) specific hand-optimized assembly
   isa/avx2/          - AVX2 only source.
   isa/avx2/gas/      - Assembly only files for GNU ASsembler (256-bit version)
   isa/avx512/        - AVX512 only source.
   isa/avx512/gas/    - Assembly only files for GNU ASsembler (AVX512 version)

*** Naming convention
v4s - Vector single precision 128-bit (4 32-bit elements)
v8s - Vector single-precision packed 256-bit (8 32-bit elements)
v2d - Vector double-precision packed 128-bit (2 64-bit elements)
v4d - Vector double-precision packed 256-bit (4 64-bit elements)


** Tests

Test Framework files are located directly under the 'tests/' folder.

tests/
     include/      - test related headers only.
     lib/          - contains external libraries necessary for testing
     lib/crlibm/   - Correctly-rounded libm
     lib/libmcr/   - Sun-micro correctly rounde libm
     lib/openlibm/ - Opensource libm
     template/     - test template directory, this should be used to write new
			tests for new functions that are not already there.
     exp2/         - exp2() related tests
