#
# Copyright (C) 2008-2026 Advanced Micro Devices, Inc. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software without
#    specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
# IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
# INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA,
# OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
# WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Inherit global environment
Import('env')
from os.path import join as joinpath
from os.path import isdir as isdir

installdir = env['installdirs']

builddir = joinpath(env['BUILDROOT'], 'src')

ldscript = joinpath('#', 'src', 'ld-syms-libm.lds')

Import('aocl_utils_install_path')

kern_incpaths = [
    '#' + Dir('.').srcnode().path,
    '#' + joinpath(Dir('.').srcnode().path, 'optimized'),
    '#' + joinpath(Dir('.').srcnode().path, 'kern')
]

use_asan = env['use_asan']

if env['HOST_OS'] != 'win32':
    ccflags = ['-Wall',
               '-W',
               '-Wstrict-prototypes',
               '-Werror',
               '-Wno-unused-parameter',
               '-fPIC',
              ]
    if use_asan == 1:
        ccflags.append('-fsanitize=address')

    # Apply -muse-unaligned-vector-move if compiler supports it (AOCC-specific, Clang-family only)
    if env.get('SUPPORTS_UNALIGNED_VEC_MOVE', False):
        ccflags.append('-muse-unaligned-vector-move')
        print("Compiler supports -muse-unaligned-vector-move")
else:
    ccflags = ['-DAVX_XOP_FMA4_FMA3',
               '-DDEBUG=0',
               '-DENABLE_AMDLIBM_API=1',
               '-DLIBABI=aocl',
               '-D__AVX2__',
               '-Dlibalm_EXPORTS',
               '/W0',
               '/MP',
               '/O2',
               '-Wno-c++11-narrowing',
               '-m64',
               '-fdiagnostics-absolute-paths',
               '/DWIN32',
               '/D_WINDOWS',
               '/DNDEBUG',
               '-march=native',
          ]
    if use_asan == 1:
        ccflags.append(['/fsanitize=address', '/Zi'])
        ccflags.remove('/O2')

if env['HOST_OS'] == 'win32':
    if env['BUILD'] == 'debug':
        env['PDB'] = 'libalm.pdb'
        ccflags.remove('/O2')

e = env.Clone()
e.Append(
    CCFLAGS=ccflags,
    CPPPATH = kern_incpaths,
    LINKERSCRIPT = ldscript,
    STATIC_AND_SHARED_OBJECTS_ARE_THE_SAME = 1
)

alm_objs = []

almenv = e.Clone()

if e['HOST_OS'] != 'win32':
    __linkflags = ['-Wl,-ealm_main',]
    __libs = ['c']

    if use_asan == 1:
        __libs.append('asan')

    almenv.Append(
        LINKFLAGS = __linkflags, # ['-T$LINKERSCRIPT']
        LIBS      = __libs,
    )
else:
    if use_asan == 1:
        almenv.Append(
            LIBS      = ['clang_rt.asan-x86_64', 'clang_rt.asan_cxx-x86_64'],
        )

# to link to libau_cpuid library
almenv.Append(CPPPATH = joinpath(aocl_utils_install_path, 'include'))
almenv.Append(CCFLAGS = '-DUSE_AOCL_UTILS')
aocl_utils_link = env['aocl_utils_link']

# NOTE: AOCC's libc++.so.1 / libc++abi.so.1 live in <aocc>/lib/ and are not
# on the system linker/loader search path. Callers building with AOCC +
# libc++ aocl-utils must supply this path themselves, e.g.:
#     scons LIBPATH=<aocc>/lib \
#           LINKFLAGS='-Wl,-rpath-link=<aocc>/lib -Wl,-rpath,<aocc>/lib' ...
# and/or export LD_LIBRARY_PATH=<aocc>/lib for runtime.

if e['HOST_OS'] != 'win32':
    import subprocess, re
    nm_cmd = env.get('NM', 'nm')

    def _detect_utils_abi(lib_path, nm_flags=None):
        """Inspect libau_cpuid symbols to determine libc++ vs libstdc++.
        Returns ('libcxx', True/False) tuple: True if libc++, False if libstdc++.
        Raises RuntimeError on ambiguous or unreadable archives."""
        try:
            cmd = [nm_cmd] + (nm_flags or []) + [lib_path]
            nm_out = subprocess.check_output(
                cmd, stderr=subprocess.DEVNULL).decode(errors='ignore')
        except (subprocess.CalledProcessError, OSError) as err:
            raise RuntimeError(
                "Unable to inspect symbols in '{}': {}."
                " Cannot validate aocl-utils ABI.".format(lib_path, err))

        has_libcxx    = bool(re.search(r'_ZNSt3__\d+',  nm_out))
        has_libstdcxx = bool(re.search(r'_ZNSt7__cxx11', nm_out))

        if has_libcxx and has_libstdcxx:
            raise RuntimeError(
                "'{}' contains both libc++ and libstdc++ symbols."
                " Rebuild aocl-utils against a single C++ runtime."
                .format(lib_path))
        if not has_libcxx and not has_libstdcxx:
            raise RuntimeError(
                "Cannot determine C++ runtime of '{}'."
                " Neither libc++ nor libstdc++ symbols found."
                .format(lib_path))
        return has_libcxx

    def _check_abi_compat(is_libcxx, cxx_path, lib_name):
        """Raise RuntimeError if the compiler and utils runtime mismatch.
        Clang expects libc++; GCC expects libstdc++."""
        is_clang = 'clang' in cxx_path
        if is_libcxx and not is_clang:
            raise RuntimeError(
                "{} was built with libc++, but the compiler is '{}'."
                " Either rebuild libm with Clang, or rebuild"
                " aocl-utils against libstdc++.".format(lib_name, cxx_path))
        if not is_libcxx and is_clang:
            raise RuntimeError(
                "{} was built with libstdc++, but the compiler is"
                " Clang ('{}') which defaults to libc++. Either rebuild"
                " aocl-utils with Clang, or rebuild libm with GCC."
                .format(lib_name, cxx_path))

    cxx_path = env.subst('$CXX')

    if int(aocl_utils_link):
        print("Linking Static libau_cpuid library")
        aocl_utils_static_lib_path = joinpath(aocl_utils_install_path, 'lib', 'libau_cpuid.a')
        aocl_utils_static_lib_path = almenv.File(aocl_utils_static_lib_path)
        almenv.Append(LIBS=aocl_utils_static_lib_path)

        is_libcxx = _detect_utils_abi(aocl_utils_static_lib_path.abspath)
        _check_abi_compat(is_libcxx, cxx_path, 'libau_cpuid.a')

        if is_libcxx:
            print("Linking libalm with libc++ (-lc++ -lc++abi)")
            for _e in (env, e, almenv):
                _e.Append(CXXFLAGS=['-stdlib=libc++'],
                          LINKFLAGS=['-stdlib=libc++'])
            almenv.Append(LIBS=['c++', 'c++abi'])
        else:
            print("Linking libalm with libstdc++ (-lstdc++)")
            almenv.Append(LIBS='stdc++')
    else:
        print("Linking Dynamic libau_cpuid library")
        aocl_utils_dynamic_lib_path = joinpath(aocl_utils_install_path, 'lib', 'libau_cpuid.so')
        aocl_utils_dynamic_lib_path = almenv.File(aocl_utils_dynamic_lib_path)
        almenv.Append(LIBS=aocl_utils_dynamic_lib_path)

        is_libcxx = _detect_utils_abi(aocl_utils_dynamic_lib_path.abspath, ['-D'])
        _check_abi_compat(is_libcxx, cxx_path, 'libau_cpuid.so')

        if is_libcxx:
            print("libau_cpuid.so depends on libc++;"
                  " ensure LD_LIBRARY_PATH contains AOCC's lib/ at runtime,"
                  " or pass LINKFLAGS='-Wl,-rpath,<aocc>/lib' to bake it.")
        else:
            print("libau_cpuid.so depends on libstdc++ (standard system path).")
else:
    if int(aocl_utils_link):
        print("Linking Static libau_cpuid library")
        aocl_utils_static_lib_path = joinpath(aocl_utils_install_path, 'lib', 'au_cpuid_static.lib')
        aocl_utils_static_lib_path = almenv.File(aocl_utils_static_lib_path)
        almenv.Append(LIBS=aocl_utils_static_lib_path)
        almenv.Append(LIBS=["msvcrt"])
    else:
        print("Linking Dynamic libau_cpuid library")
        aocl_utils_static_lib_path = joinpath(aocl_utils_install_path, 'lib', 'au_cpuid.lib')
        aocl_utils_static_lib_path = almenv.File(aocl_utils_static_lib_path)
        almenv.Append(LIBS=aocl_utils_static_lib_path)

subdirs = ['isa', 'optimized', 'iface', 'arch', 'ref']
for d in subdirs:
    denv = almenv.Clone()
    sdir = joinpath(denv['CWD'], d)
    denv.Append(
        CWD = sdir
    )
    alm_objs += SConscript('%s/SConscript'%d,
                exports = {'env' : denv},
                duplicate = 0,
                            src_dir = sdir,
                            variant_dir = joinpath(builddir, '%s'%d))

lib_excludes = ['alm_env.c']
lib_srcs = Glob('*.[c]', exclude=lib_excludes)

alm_objs += almenv.StaticObject(lib_srcs)

if e['HOST_OS'] != 'win32':
    libm = almenv.StaticLibrary('alm', alm_objs)
    libmso = almenv.SharedLibrary('alm', alm_objs)
else:
    libm = almenv.StaticLibrary('libalm-static', source = [alm_objs, joinpath(aocl_utils_install_path, 'lib','au_cpuid_static.lib')])
    almenv['WINDOWS_INSERT_DEF']=1
    libmso = almenv.SharedLibrary('libalm', alm_objs, no_import_lib=False)

#add include headers as part of the install
alm_headers = ['amdlibm.h', 'amdlibm_vec.h']
alm_external_headers = list(map(lambda x : joinpath(env['INCPATH'], 'external', x), alm_headers))
alm_examples_src = joinpath('#', 'examples', 'src')
alm_examples_makefile = joinpath('#', 'examples', 'Makefile')
alm_examples_readme = joinpath('#', 'examples', 'README')

if 'install' in COMMAND_LINE_TARGETS:
    almenv.Alias('install', almenv.Install(installdir['lib'], [libmso, libm]))
    almenv.Alias("install", almenv.Install(installdir['include'], [alm_external_headers]))
    almenv.Alias('install', almenv.Install(installdir['examples'], [alm_examples_src,
                                                                    alm_examples_makefile,
                                                                    alm_examples_readme]))

fast_libm = SConscript('fast/SConscript',
                       exports = {'env' : e},
                       duplicate = 0,
                       src_dir = '#src/fast',
                       variant_dir = joinpath(builddir, 'fast'))

if e['HOST_OS'] != 'win32':
    compat_libm = SConscript('compat/SConscript',
                       exports = {'env' : e},
                       duplicate = 0,
                       src_dir = '#src/compat',
                       variant_dir = joinpath(builddir, 'compat'))

Depends(libmso, ldscript)
if e['HOST_OS'] != 'win32':
    Return('compat_libm', 'fast_libm', 'libm', 'libmso')
else:
    Return('fast_libm', 'libm', 'libmso')