# Copyright (C) 2018, AMD. All rights Reserved
#
# Author: Prem Mallappa <pmallapp@amd.com>

# Inherit global environment
Import('env')

e = env.Clone()
e.Append(
#	 CPPPATH = [''],
#        CCFLAGS = [],
	)

# The set of source files associated with this SConscript file.
source = 				\
	Glob('isa/avx2/gas/*.[cS]') 		#+	\

#	Glob('isa/avx/gas/*.[cS]') +	\
#	Glob('isa/avx512/gas/*.[cS]') +\

#print('lib sources' , source)

objects = e.StaticObject(source)

libm = e.StaticLibrary('amdlibm', objects)

Return('libm')

