/*
* This file is automatically generated by the build process
* DO NOT EDIT!
*/

static const char VERSION_STRING[] = "fa9795e (modified)";

static const char* alm_get_build(void);
static const char* alm_get_build(void)
{
        return VERSION_STRING;
}
